Repository Sowee0/playlist-sync, pull requests merged in 2022-10, with the labels that each got.

#2 Get YTM track info
  bin/Activate.ps1
  bin/activate
  bin/activate.csh
  bin/activate.fish
  bin/easy_install
  bin/easy_install-3.8
  bin/pip
  bin/pip3
  bin/pip3.8
  bin/python
  bin/python3
  lib64
  pyvenv.cfg
  sync_python.py
Labels: hacktoberfest-accepted

#3 Get spotify track info
  sync_python.py
Labels: hacktoberfest-accepted

#4 Get tracks for both services
  credentials.json
  sync_python.py
Labels: hacktoberfest-accepted

#5 Get ids to add to playlists
  credentials.json.example
  sync_python.py
Labels: hacktoberfest-accepted

#8 Adding addToSpotify method
  sync_python.py
Labels: enhancement, hacktoberfest-accepted

#9 Adding the addToYtm
  sync_python.py
Labels: enhancement, hacktoberfest-accepted

#10 Fixing the missing track vars and adding the calls for the new methods
  sync_python.py
Labels: bug, hacktoberfest-accepted
